<?php

namespace App\View\Components;

use Closure;
use Illuminate\View\Component;
use Illuminate\Contracts\View\View;

class Portfolio extends Component
{
    public array $items = [];
    
    /**
     * Create a new component instance.
     */
    public function __construct()
    {
        $this->items = [
            [
                'title' => 'Code Chronicles',
                'description' => 'Articles about PHP, Laravel and more generated by OpenAI',
                'image' => url('/img/codechronicles.png'),
                'link' => 'https://codechronicles.eu'
            ],
            [
                'title' => 'Movies and Tv Shows',
                'description' => 'Netflix clone, where you can watch only the trailer',
                'image' => url('/img/netflix.png'),
                'link' => 'https://moviestvshows.fun'
            ],
        ];
    }

    
    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        return view('components.home.portfolio');
    }
}
